[theme]
base = "dark"
backgroundColor = "#09090f"
secondaryBackgroundColor = "#0f0f1a"
textColor = "#f0f0ff"
primaryColor = "#7c6af7"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
